Updating to work on Jessie

diff --git a/tools/daqhats_read_eeproms b/tools/daqhats_read_eeproms
--- a/tools/daqhats_read_eeproms
+++ b/tools/daqhats_read_eeproms
@@ -12,11 +12,15 @@ if [ -e "/dev/i2c-0" ]; then
 elif [ -e "/dev/i2c-3" ]; then
    BUS=3
 else
-   dtoverlay i2c-gpio i2c_gpio_sda=0 i2c_gpio_scl=1 bus=3
+   dtoverlay i2c-gpio i2c_gpio_sda=0 i2c_gpio_scl=1 bus=3 > /dev/null 2>&1
    rc=$?
    if [ $rc != 0 ]; then
-      echo "Loading of i2c-gpio dtoverlay failed. Do an rpi-update (and maybe apt update; apt upgrade)."
-      exit $rc
+      dtoverlay i2c-gpio i2c_gpio_sda=0 i2c_gpio_scl=1
+      rc=$?
+      if [ $rc != 0 ]; then
+         echo "Loading of i2c-gpio dtoverlay failed. Do an rpi-update (and maybe apt update; apt upgrade)."
+         exit $rc
+      fi
    fi
    if [ -e "/dev/i2c-3" ]; then
       BUS=3
